// Bookmarklets: the extension-free way to fill the See Tickets registration
// form (2026-09-16; hybrid live-fetch added 2026-09-17).
//
// Why: Lightning Autofill (the renamed "AutoFill Options") caps its free plan
// at 10 profile executions a day, so anyone who tests or reloads on sale
// morning can be locked out at the moment it matters. A bookmarklet is a
// bookmark whose address is a snippet of JavaScript; click it on the
// registration page and it fills the boxes. No extension, no account, no
// quota, and it works in Chrome, Edge, Firefox and Safari.
//
// The data comes from the SAME autofill files the extension uses
// (GET /files/{filename}, AutoFill's CSV export format, generated by
// Common/BusWankers.cs), parsed here into groups. So nothing changes on the
// backend and the extension path keeps working for anyone who wants it.
//
// Data freshness - the hybrid design (2026-09-17): a bookmarklet's data used
// to be baked in once, at generation time, and then sat unchanged in the
// user's real browser bookmarks for as long as they kept it - stale the
// moment the underlying spreadsheet was re-ingested with a correction. Now
// every bookmarklet ALSO carries the URL of its sale's live, structured group
// data (GET /files/{filename}/groups - see UploadServiceController.
// DownloadGroups and AutofillStore.SaveGroupsAsync), and on click it tries
// that first: a short, timed fetch, cross-origin, from whatever page happens
// to be open (the actual registration page, on a domain this app has no way
// to know in advance - the service's CORS policy already allows any origin,
// see Program.cs). Only if that fails - offline, the request times out, the
// registration page's own CSP blocks it, nothing's been re-ingested since the
// bookmark was made - does it fall back to the data embedded at generation
// time, exactly as before. So a bookmark made in August and clicked in
// September gets August's fallback only in the worst case; normally it gets
// whatever is live right now. There is deliberately no offline mode at all
// for this fetch beyond that one fallback: no retry loop, no long timeout -
// sale mornings have a 10-minute registration window, and a bookmarklet that
// might hang on a dead network is worse than one that gives up in four
// seconds and uses what it already has.
//
// The fill logic lives in FILL_SOURCE as a string, because it has to be
// embedded verbatim in the bookmarklet URL. runFillOnThisPage() runs the very
// same source against our own Test Form, so what's tested is what ships -
// live fetch included, since the Test Form is served from this same origin
// and so is a genuine (same-origin) rehearsal of the live-fetch path, not
// just the fallback.

// ---------------------------------------------------------------------------
// Parsing the AutoFill CSV
// ---------------------------------------------------------------------------

// Minimal CSV line splitter: fields may be double-quoted (our generator
// quotes the rule name/value/site); no embedded newlines are ever produced.
function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; } else { inQuotes = false; }
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ',') {
      out.push(cur);
      cur = '';
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out.map((s) => s.trim());
}

// "Group-A" -> "A", "Coach Group-A" -> "A", "Group-1" -> "1"; anything else
// as-is. No "^" anchor: the backend now prefixes the profile Name with the
// sale's own short label (see UploadServiceController.SaleFolderLabelFor /
// GenerateAutofillTextFromGroups, 2026-09-18) so two sales that both happen
// to have a "Group A" are never ambiguous once imported into AutoFill
// Options/Lightning Autofill - but the RAW label recovered here still has
// to be just the bare letter, because it's matched against the live groups
// JSON's own (never-prefixed) label field - see liveMembersFor below and
// ToGroupsDocument on the backend.
const groupLabelFromProfileName = (name) => {
  const m = /Group-(.+)$/i.exec(name || '');
  return m ? m[1] : (name || '');
};

// "Coach Group A" - the sale-qualified group name shown everywhere a group
// is named to a person: bookmark titles, their on-page confirmation
// banners, the whole-sale bookmarklet's tap-to-choose picker, and the
// Documentation/Groups tabs' group headings (2026-09-18) - so two sales
// that both happen to have a "Group A" (e.g. Coach and General) are never
// ambiguous. saleFolderLabel is SALE_INFO[...].folderLabel (see
// saleInfo.js) - "Coach", "General", "Coach Resale", "General Resale";
// falls back to a bare "Group A" if one was never known.
export const groupDisplayLabel = (saleFolderLabel, label) =>
  saleFolderLabel ? `${saleFolderLabel} Group ${label}` : `Group ${label}`;

// Parses an autofill file into groups:
//   [{ code: 'c1', label: 'A', name: 'Group-A', members: [{ registrationId, postCode }] }]
// Members are in slot order; padding slots (blank reg number AND postcode)
// are dropped, so members.length is the real group size.
export function parseAutofillCsv(text) {
  const lines = String(text || '').split(/\r?\n/);
  let section = null; // 'profiles' | 'rules' | 'options'
  const profiles = new Map(); // code -> { code, label, name, slots: Map<slot, {registrationId, postCode}> }
  const order = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('### AUTOFILL PROFILES')) { section = 'profiles'; continue; }
    if (line.startsWith('### AUTOFILL RULES')) { section = 'rules'; continue; }
    if (line.startsWith('### AUTOFILL OPTIONS')) { section = 'options'; continue; }

    const f = splitCsvLine(line);
    if (section === 'profiles') {
      if (/^profile id$/i.test(f[0] || '')) continue; // header row
      const code = f[0];
      if (!/^c\d+$/i.test(code)) continue;
      const name = f[1] || code;
      profiles.set(code, { code, name, label: groupLabelFromProfileName(name), slots: new Map() });
      order.push(code);
    } else if (section === 'rules') {
      if (/^rule id$/i.test(f[0] || '')) continue; // header row
      // Rule ID, Type, Name, Value, Site, Mode, Profile
      const fieldName = f[2] || '';
      const value = f[3] || '';
      const code = f[6] || '';
      const m = /registrations[^0-9]*(\d+)[^a-z]*(registrationid|postcode)/i.exec(fieldName);
      if (!m) continue;
      const profile = profiles.get(code);
      if (!profile) continue;
      const slot = Number(m[1]);
      const entry = profile.slots.get(slot) || { registrationId: '', postCode: '' };
      if (m[2].toLowerCase() === 'registrationid') entry.registrationId = value.trim();
      else entry.postCode = value.trim();
      profile.slots.set(slot, entry);
    }
  }

  return order.map((code) => {
    const p = profiles.get(code);
    const members = [...p.slots.entries()]
      .sort((a, b) => a[0] - b[0])
      .map(([, e]) => e)
      .filter((e) => e.registrationId || e.postCode);
    return { code: p.code, name: p.name, label: p.label, members };
  });
}

// ---------------------------------------------------------------------------
// The fill routine (embedded in every bookmarklet)
// ---------------------------------------------------------------------------

// Runs with four variables in scope: M (the embedded fallback - array of
// [registrationId, postCode], in slot order), G (the raw group label, e.g.
// "A"), U (the absolute URL of this sale's live group data, or '' if
// none was available when the bookmark was generated), and S (the sale's
// own short display label, e.g. "Coach" - see groupDisplayLabel above; ''
// if none was known, in which case the confirmation banner below just says
// "Group A" rather than "Coach Group A"). Deliberately
// old-school JS (no arrow functions, template literals, let/const) so it
// runs on any browser someone might be using on the day - fetch/Promise
// themselves are assumed available (every browser released since 2016 has
// them; a browser old enough not to would already be unable to load the
// registration page itself), but everything here uses plain functions and
// .then/.catch rather than async/await. Keep it self-contained - it cannot
// reference anything from this module.
//
// Matching strategy for the page's input boxes, in order:
//   1. inputs whose id OR name matches registrations…N…RegistrationId /
//      …Postcode (case-insensitive; covers registrations_0__RegistrationId,
//      registrations[0].RegistrationId and reasonable variants);
//   2. failing that, inputs by class (See Tickets uses .numeric / .postcode)
//      or by id containing "egistration" / "ostcode", paired up in order.
// Values are written through the native setter and followed by input/change
// events, so plain, jQuery-validated AND React forms all see a real edit.
//
// Data source, in order: a live fetch of U (aborted after 4 seconds so a
// dead network can't stall someone in the registration window), falling back
// to M if U is empty, the fetch fails, times out, the response isn't OK, or
// it doesn't contain this group's label. Either way the confirmation banner
// says which one was actually used ("live data" / "offline backup data"),
// so nobody has to guess.
export const FILL_SOURCE = `
(function(){
  function nat(el, v) {
    var proto = Object.getPrototypeOf(el);
    var d = Object.getOwnPropertyDescriptor(proto, 'value') || Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value');
    if (d && d.set) { d.set.call(el, v); } else { el.value = v; }
    try { el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); }
    catch (e) { var ev = document.createEvent('HTMLEvents'); ev.initEvent('change', true, false); el.dispatchEvent(ev); }
  }
  function find(i, kind) {
    var re = new RegExp('registrations[^0-9]*' + i + '[^a-z0-9]+' + kind + '$', 'i');
    var ins = document.querySelectorAll('input');
    for (var k = 0; k < ins.length; k++) {
      var e = ins[k];
      if (re.test(e.id || '') || re.test(e.name || '')) return e;
    }
    return null;
  }
  var slots = [];
  for (var i = 0; i < 20; i++) {
    var r = find(i, 'registrationid'), p = find(i, 'postcode');
    if (!r && !p) break;
    slots.push([r, p]);
  }
  if (!slots.length) {
    var regs = document.querySelectorAll('input.numeric, input[id*="egistration"], input[name*="egistration"]');
    var posts = document.querySelectorAll('input.postcode, input[id*="ostcode"], input[name*="ostcode"]');
    for (var j = 0; j < Math.max(regs.length, posts.length); j++) slots.push([regs[j] || null, posts[j] || null]);
  }
  if (!slots.length) {
    alert('Bus Wankers: no registration boxes found on this page. Are you on the Glastonbury registration page?');
    return;
  }

  function showBanner(msg, isProblem) {
    try {
      var old = document.getElementById('bw-fill-banner'); if (old) old.parentNode.removeChild(old);
      var b = document.createElement('div');
      b.id = 'bw-fill-banner';
      b.textContent = msg + ' (click to dismiss)';
      b.setAttribute('style', 'position:fixed;top:0;left:0;right:0;z-index:2147483647;background:' + (isProblem ? '#b3261e' : '#1a7f37') + ';color:#fff;font:15px/1.4 Arial,sans-serif;padding:12px 16px;text-align:center;box-shadow:0 2px 6px rgba(0,0,0,.3);cursor:pointer');
      b.onclick = function () { if (b.parentNode) b.parentNode.removeChild(b); };
      document.body.appendChild(b);
      setTimeout(function () { if (b.parentNode) b.parentNode.removeChild(b); }, 15000);
    } catch (e) { alert(msg); }
  }

  function fillWithData(members, source) {
    var filled = 0;
    for (var s = 0; s < slots.length; s++) {
      var m = members[s] || ['', ''];
      if (slots[s][0]) nat(slots[s][0], m[0]);
      if (slots[s][1]) nat(slots[s][1], m[1]);
      if (m[0] && slots[s][0]) filled++;
    }
    var missing = members.length > slots.length ? members.slice(slots.length) : [];
    var groupName = (S ? S + ' Group ' : 'Group ') + G;
    var msg = 'Bus Wankers - ' + groupName + ' (' + source + '): filled ' + filled + ' of ' + members.length + ' people.';
    if (missing.length) {
      msg += ' This page only has ' + slots.length + ' slots, so NOT entered: ' + missing.map(function (x) { return x[0]; }).join(', ') + '.';
    }
    msg += ' Check the boxes, then click Proceed.';
    showBanner(msg, missing.length > 0);
  }

  function liveMembersFor(body) {
    var groups = (body && body.groups) || [];
    for (var i = 0; i < groups.length; i++) {
      if (String(groups[i].label) === String(G) && groups[i].members && groups[i].members.length) {
        var out = [];
        for (var j = 0; j < groups[i].members.length; j++) {
          var mem = groups[i].members[j];
          out.push([String(mem.registrationId || ''), String(mem.postCode || '').replace(/\\s+/g, '').toUpperCase()]);
        }
        return out;
      }
    }
    return null;
  }

  if (!U || !window.fetch) {
    fillWithData(M, 'offline backup data');
    return;
  }

  var settled = false;
  var timer = setTimeout(function () {
    if (settled) return;
    settled = true;
    fillWithData(M, 'offline backup data – live check timed out');
  }, 4000);

  fetch(U, { cache: 'no-store', mode: 'cors', credentials: 'omit' }).then(function (r) {
    if (!r.ok) throw new Error('bad status');
    return r.json();
  }).then(function (body) {
    if (settled) return;
    var live = liveMembersFor(body);
    if (!live) throw new Error('group not present live');
    settled = true;
    clearTimeout(timer);
    fillWithData(live, 'live data');
  }).catch(function () {
    if (settled) return;
    settled = true;
    clearTimeout(timer);
    fillWithData(M, 'offline backup data');
  });
})();
`;

// Postcodes go in upper case with no spaces - that's how the See Tickets
// form displays them (text-transform: uppercase) and how the roster has
// them; it also avoids a trailing-space mismatch against the registration.
const normalisePostcode = (s) => String(s || '').replace(/\s+/g, '').toUpperCase();

const membersToTuples = (members) =>
  members.map((m) => [String(m.registrationId || '').trim(), normalisePostcode(m.postCode)]);

// ---------------------------------------------------------------------------
// The complete bookmarklet
// ---------------------------------------------------------------------------

// The complete bookmarklet source for one group, as plain JavaScript. Wrapped
// in its own function so M, G, U and S never leak onto the host page as
// globals. groupsUrl is the sale's live group-data URL (see groupsUrlFor in
// api/autofillApi.js) - optional so a sale with nothing ingested yet still
// gets a working (fallback-only) bookmarklet; when given, it travels inside
// the bookmark itself so FILL_SOURCE can try it live at click time (see the
// comment on FILL_SOURCE above for the fallback behaviour). saleFolderLabel
// (2026-09-18) is SALE_INFO[...].folderLabel - baked in so the confirmation
// banner reads "Coach Group A" rather than an ambiguous "Group A"; optional,
// same as groupsUrl, for any caller that doesn't have one to hand.
export function bookmarkletSource(group, groupsUrl = '', saleFolderLabel = '') {
  const M = JSON.stringify(membersToTuples(group.members));
  const G = JSON.stringify(group.label);
  const U = JSON.stringify(groupsUrl || '');
  const S = JSON.stringify(saleFolderLabel || '');
  return `(function(){var M=${M},G=${G},U=${U},S=${S};${FILL_SOURCE}})();`;
}

// The javascript: URL to put in the bookmark. Percent-encoded so nothing in
// the source (quotes, #, spaces) can break the URL; browsers decode
// javascript: URLs before running them.
export function bookmarkletHref(group, groupsUrl = '', saleFolderLabel = '') {
  return `javascript:${encodeURIComponent(bookmarkletSource(group, groupsUrl, saleFolderLabel))}`;
}

// A sensible bookmark name: "Glasto 2027 - Fill Coach Group A" (see
// groupDisplayLabel above - saleFolderLabel is SALE_INFO[...].folderLabel,
// 2026-09-18, so two sales that both have a "Group A" are never ambiguous in
// the bookmarks bar either). Deliberately no longer carries a data
// version/vintage - see the FILL_SOURCE comment above for why: the bookmark
// itself checks live at click time and says in its own confirmation banner
// whether it used live or fallback data, which is a more honest answer than
// a name baked in once at generation time could ever be.
export const bookmarkletTitle = (group, year, saleFolderLabel) =>
  `Glasto ${year} - Fill ${groupDisplayLabel(saleFolderLabel, group.label)}`;

// Runs the identical fill routine against THIS page (the Test Form tab), so
// "Try it on the Test Form" exercises exactly what the bookmark will do -
// including the live fetch, since the Test Form is same-origin with this app
// and so is a genuine rehearsal of that path, not just the fallback.
export function runFillOnThisPage(group, groupsUrl = '', saleFolderLabel = '') {
  const M = membersToTuples(group.members);
  const G = group.label;
  const U = groupsUrl || '';
  const S = saleFolderLabel || '';
  // eslint-disable-next-line no-new-func
  const fn = new Function('M', 'G', 'U', 'S', FILL_SOURCE);
  fn(M, G, U, S);
}

// ---------------------------------------------------------------------------
// One bookmark for the WHOLE sale (2026-09-17)
// ---------------------------------------------------------------------------
//
// Installing a bookmark per group, or downloading a folder and finding your
// browser's own "Import bookmarks from HTML" menu, is still more steps than
// some people want handed to them - and a page cannot install a bookmark
// (or a folder of them) for you in one click; browsers deliberately don't
// let web content write to the bookmarks bar, full stop, which is why the
// folder route below exists at all. The one thing a page CAN do in a single
// user gesture is let you drag ONE link onto the bar - so this is that: one
// bookmark, covering every group in the sale. On click it live-fetches (or
// falls back to the data embedded at generation time, on exactly the same
// terms as FILL_SOURCE above) every group, then shows a plain tap-to-choose
// list so the person picks their own group before it fills the page. One
// install, one extra tap on the day - as close to "spoon-fed" as this can
// get without asking someone to trust a browser extension.
export const SALE_FILL_SOURCE = `
(function(){
  function nat(el, v) {
    var proto = Object.getPrototypeOf(el);
    var d = Object.getOwnPropertyDescriptor(proto, 'value') || Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value');
    if (d && d.set) { d.set.call(el, v); } else { el.value = v; }
    try { el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); }
    catch (e) { var ev = document.createEvent('HTMLEvents'); ev.initEvent('change', true, false); el.dispatchEvent(ev); }
  }
  function find(i, kind) {
    var re = new RegExp('registrations[^0-9]*' + i + '[^a-z0-9]+' + kind + '$', 'i');
    var ins = document.querySelectorAll('input');
    for (var k = 0; k < ins.length; k++) {
      var e = ins[k];
      if (re.test(e.id || '') || re.test(e.name || '')) return e;
    }
    return null;
  }
  var slots = [];
  for (var i = 0; i < 20; i++) {
    var r = find(i, 'registrationid'), p = find(i, 'postcode');
    if (!r && !p) break;
    slots.push([r, p]);
  }
  if (!slots.length) {
    var regs = document.querySelectorAll('input.numeric, input[id*="egistration"], input[name*="egistration"]');
    var posts = document.querySelectorAll('input.postcode, input[id*="ostcode"], input[name*="ostcode"]');
    for (var j = 0; j < Math.max(regs.length, posts.length); j++) slots.push([regs[j] || null, posts[j] || null]);
  }
  if (!slots.length) {
    alert('Bus Wankers: no registration boxes found on this page. Are you on the Glastonbury registration page?');
    return;
  }

  function showBanner(msg, isProblem) {
    try {
      var old = document.getElementById('bw-fill-banner'); if (old) old.parentNode.removeChild(old);
      var b = document.createElement('div');
      b.id = 'bw-fill-banner';
      b.textContent = msg + ' (click to dismiss)';
      b.setAttribute('style', 'position:fixed;top:0;left:0;right:0;z-index:2147483647;background:' + (isProblem ? '#b3261e' : '#1a7f37') + ';color:#fff;font:15px/1.4 Arial,sans-serif;padding:12px 16px;text-align:center;box-shadow:0 2px 6px rgba(0,0,0,.3);cursor:pointer');
      b.onclick = function () { if (b.parentNode) b.parentNode.removeChild(b); };
      document.body.appendChild(b);
      setTimeout(function () { if (b.parentNode) b.parentNode.removeChild(b); }, 15000);
    } catch (e) { alert(msg); }
  }

  function fillWithData(label, members, source) {
    var filled = 0;
    for (var s = 0; s < slots.length; s++) {
      var m = members[s] || ['', ''];
      if (slots[s][0]) nat(slots[s][0], m[0]);
      if (slots[s][1]) nat(slots[s][1], m[1]);
      if (m[0] && slots[s][0]) filled++;
    }
    var missing = members.length > slots.length ? members.slice(slots.length) : [];
    var groupName = (S ? S + ' Group ' : 'Group ') + label;
    var msg = 'Bus Wankers - ' + groupName + ' (' + source + '): filled ' + filled + ' of ' + members.length + ' people.';
    if (missing.length) {
      msg += ' This page only has ' + slots.length + ' slots, so NOT entered: ' + missing.map(function (x) { return x[0]; }).join(', ') + '.';
    }
    msg += ' Check the boxes, then click Proceed.';
    showBanner(msg, missing.length > 0);
  }

  function removePicker() {
    var old = document.getElementById('bw-picker');
    if (old && old.parentNode) old.parentNode.removeChild(old);
  }

  function showPicker(groups, source) {
    removePicker();
    var overlay = document.createElement('div');
    overlay.id = 'bw-picker';
    overlay.setAttribute('style', 'position:fixed;z-index:2147483647;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.55);display:flex;align-items:center;justify-content:center;font:15px/1.4 Arial,sans-serif;padding:16px;box-sizing:border-box;');
    var box = document.createElement('div');
    box.setAttribute('style', 'background:#fff;color:#222;border-radius:10px;padding:18px;max-width:340px;width:100%;max-height:80vh;overflow:auto;box-shadow:0 8px 28px rgba(0,0,0,.45);box-sizing:border-box;');
    var title = document.createElement('div');
    title.textContent = 'Bus Wankers - which group are you?';
    title.setAttribute('style', 'font-weight:bold;font-size:1.05em;margin-bottom:4px;');
    box.appendChild(title);
    var sub = document.createElement('div');
    sub.textContent = 'Tap your group below (' + source + ').';
    sub.setAttribute('style', 'color:#666;margin-bottom:12px;font-size:13px;');
    box.appendChild(sub);
    var list = document.createElement('div');
    list.setAttribute('style', 'display:flex;flex-direction:column;gap:6px;');
    for (var gi = 0; gi < groups.length; gi++) {
      (function (g) {
        var btn = document.createElement('button');
        btn.type = 'button';
        btn.textContent = (S ? S + ' Group ' : 'Group ') + g.label + ' (' + g.members.length + (g.members.length === 1 ? ' person' : ' people') + ')';
        btn.setAttribute('style', 'display:block;width:100%;padding:11px 14px;border:1px solid #ccc;border-radius:7px;background:#f7f9fb;cursor:pointer;font:inherit;text-align:left;');
        btn.onclick = function () {
          removePicker();
          fillWithData(g.label, g.members, source);
        };
        list.appendChild(btn);
      })(groups[gi]);
    }
    box.appendChild(list);
    var cancel = document.createElement('button');
    cancel.type = 'button';
    cancel.textContent = 'Cancel';
    cancel.setAttribute('style', 'margin-top:14px;width:100%;padding:8px;border:none;background:transparent;color:#888;cursor:pointer;font:inherit;');
    cancel.onclick = removePicker;
    box.appendChild(cancel);
    overlay.appendChild(box);
    overlay.onclick = function (e) { if (e.target === overlay) removePicker(); };
    document.body.appendChild(overlay);
  }

  function withGroups(groups, source) {
    if (!groups || !groups.length) {
      alert('Bus Wankers: no group data available - nothing has been ingested for this sale yet.');
      return;
    }
    // Always show the picker, even when the sale only has one group, so
    // behaviour is identical regardless of group count (2026-09-18).
    showPicker(groups, source);
  }


  if (!U || !window.fetch) {
    withGroups(ALLM, 'offline backup data');
    return;
  }

  var settled = false;
  var timer = setTimeout(function () {
    if (settled) return;
    settled = true;
    withGroups(ALLM, 'offline backup data – live check timed out');
  }, 4000);

  fetch(U, { cache: 'no-store', mode: 'cors', credentials: 'omit' }).then(function (r) {
    if (!r.ok) throw new Error('bad status');
    return r.json();
  }).then(function (body) {
    if (settled) return;
    var raw = (body && body.groups) || [];
    var live = [];
    for (var i = 0; i < raw.length; i++) {
      var rm = raw[i].members || [];
      var out = [];
      for (var j = 0; j < rm.length; j++) {
        var mem = rm[j];
        out.push([String(mem.registrationId || ''), String(mem.postCode || '').replace(/\\s+/g, '').toUpperCase()]);
      }
      live.push({ label: String(raw[i].label), members: out });
    }
    if (!live.length) throw new Error('no groups live');
    settled = true;
    clearTimeout(timer);
    withGroups(live, 'live data');
  }).catch(function () {
    if (settled) return;
    settled = true;
    clearTimeout(timer);
    withGroups(ALLM, 'offline backup data');
  });
})();
`;

// groups: the sale's full group list (parseAutofillCsv shape). Wrapped in
// its own function so ALLM, U and S never leak onto the host page as
// globals - same pattern as bookmarkletSource above, just carrying every
// group's fallback data instead of one. saleFolderLabel (2026-09-18) is
// SALE_INFO[...].folderLabel - baked in so both the picker's buttons and
// the fill confirmation banner read "Coach Group A" rather than an
// ambiguous "Group A" (this one bookmark only ever lists ITS OWN sale's
// groups, so the picker itself was never ambiguous - but someone who's
// installed a whole-sale bookmark for more than one sale, e.g. Coach and
// General, would otherwise get an identical-looking "Group A" confirmation
// banner from either one).
export function saleBookmarkletSource(groups, groupsUrl = '', saleFolderLabel = '') {
  const ALLM = JSON.stringify(groups.map((g) => ({ label: g.label, members: membersToTuples(g.members) })));
  const U = JSON.stringify(groupsUrl || '');
  const S = JSON.stringify(saleFolderLabel || '');
  return `(function(){var ALLM=${ALLM},U=${U},S=${S};${SALE_FILL_SOURCE}})();`;
}

export function saleBookmarkletHref(groups, groupsUrl = '', saleFolderLabel = '') {
  return `javascript:${encodeURIComponent(saleBookmarkletSource(groups, groupsUrl, saleFolderLabel))}`;
}

// "Coach Filler" / "General Filler" / "Coach Resale Filler" (2026-09-18) -
// short and sale-specific rather than a long "Glasto 2027 - Fill My Group
// (Coach)" title, since this is the ONE bookmark most people will ever
// see in their bar and it needs to read at a glance. saleFolderLabel is
// always SALE_INFO[...].folderLabel (see groupDisplayLabel above), so two
// sales' bookmarks are never confusable with each other either. Works for
// everyone on that sale; which group it fills is picked on click, not
// baked into the title (there's only one of these per sale, so there's
// nothing to disambiguate the way per-group titles need to).
export const saleBookmarkletTitle = (saleFolderLabel, year) =>
  `${saleFolderLabel} Filler`;

// Runs the identical routine against THIS page (the Test Form tab) - same
// rationale as runFillOnThisPage above: same source, same live-fetch path,
// genuine rehearsal of the picker included.
export function runSaleFillOnThisPage(groups, groupsUrl = '', saleFolderLabel = '') {
  const ALLM = groups.map((g) => ({ label: g.label, members: membersToTuples(g.members) }));
  const U = groupsUrl || '';
  const S = saleFolderLabel || '';
  // eslint-disable-next-line no-new-func
  const fn = new Function('ALLM', 'U', 'S', SALE_FILL_SOURCE);
  fn(ALLM, U, S);
}

// ---------------------------------------------------------------------------
// A whole sale's bookmarks as an importable folder
// ---------------------------------------------------------------------------

const escapeHtml = (s) => String(s)
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

// The "Netscape bookmark file" format every browser imports (Chrome/Edge:
// Bookmarks > Import bookmarks and settings > HTML file; Firefox: Library >
// Import and Backup > Import Bookmarks from HTML; Safari: File > Import From >
// Bookmarks HTML File). One folder, named `folderName`, holding a bookmark
// per group. The folder is placed inside the file's "toolbar" folder
// (PERSONAL_TOOLBAR_FOLDER) so browsers that honour it put it straight on
// the bookmarks bar; the others land it in an "Imported" folder, from where
// it can be dragged onto the bar - the instructions say so.
//
// The bookmarklet hrefs are percent-encoded (see bookmarkletHref), so they
// contain no quotes or ampersands and are safe inside the HREF attribute.
// groupsUrl flows through to every bookmarklet's own href, so each bookmark
// in the folder can check live for itself. saleFolderLabel (2026-09-18)
// flows through the same way, so every bookmark's title and confirmation
// banner reads "Coach Group A" rather than an ambiguous "Group A".
export function bookmarkFolderHtml(groups, folderName, year, groupsUrl = '', saleFolderLabel = '') {
  const items = groups
    .map((g) => `            <DT><A HREF="${bookmarkletHref(g, groupsUrl, saleFolderLabel)}">${escapeHtml(bookmarkletTitle(g, year, saleFolderLabel))}</A>`)
    .join('\n');
  const stamp = Math.floor(Date.now() / 1000);
  return `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
    <DT><H3 ADD_DATE="${stamp}" LAST_MODIFIED="${stamp}" PERSONAL_TOOLBAR_FOLDER="true">Bookmarks bar</H3>
    <DL><p>
        <DT><H3 ADD_DATE="${stamp}" LAST_MODIFIED="${stamp}">${escapeHtml(folderName)}</H3>
        <DL><p>
${items}
        </DL><p>
    </DL><p>
</DL><p>
`;
}

// "Glasto Coach Bookmarks" - the folder name Hugh asked for, per sale. No
// longer version-suffixed (see bookmarkletTitle above): re-downloading isn't
// something the hybrid design compels you to do the moment the data
// changes - the live fetch already picks that up on the next click - so a
// single stable, evergreen folder name is more honest than one that implies
// a new download is needed each time it changes.
export const bookmarkFolderName = (saleFolderLabel) =>
  `Glasto ${saleFolderLabel} Bookmarks`;

// A filename for the download: "Glasto Coach Bookmarks.html".
export const bookmarkFolderFileName = (saleFolderLabel) =>
  `${bookmarkFolderName(saleFolderLabel)}.html`;
