// Bookmarklets: the extension-free way to fill the See Tickets registration
// form (2026-09-16).
//
// Why: Lightning Autofill (the renamed "AutoFill Options") caps its free plan
// at 10 profile executions a day, so anyone who tests or reloads on sale
// morning can be locked out at the moment it matters. A bookmarklet is a
// bookmark whose address is a snippet of JavaScript; click it on the
// registration page and it fills the boxes. No extension, no account, no
// quota, no network on the day (the group's reg numbers and postcodes are
// embedded in it), and it works in Chrome, Edge, Firefox and Safari.
//
// The data comes from the SAME autofill files the extension uses
// (GET /files/{filename}, AutoFill's CSV export format, generated by
// Common/BusWankers.cs), parsed here into groups. So nothing changes on the
// backend and the extension path keeps working for anyone who wants it.
//
// The fill logic lives in FILL_SOURCE as a string, because it has to be
// embedded verbatim in the bookmarklet URL. runFillOnThisPage() runs the very
// same source against our own Test Form, so what's tested is what ships.

// ---------------------------------------------------------------------------
// Parsing the AutoFill CSV
// ---------------------------------------------------------------------------

// Minimal CSV line splitter: fields may be double-quoted (our generator
// quotes the rule name/value/site); no embedded newlines are ever produced.
function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; } else { inQuotes = false; }
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ',') {
      out.push(cur);
      cur = '';
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out.map((s) => s.trim());
}

// "Group-A" -> "A", "Group-1" -> "1"; anything else as-is.
const groupLabelFromProfileName = (name) => {
  const m = /^Group-(.+)$/i.exec(name || '');
  return m ? m[1] : (name || '');
};

// Parses an autofill file into groups:
//   [{ code: 'c1', label: 'A', name: 'Group-A', members: [{ registrationId, postCode }] }]
// Members are in slot order; padding slots (blank reg number AND postcode)
// are dropped, so members.length is the real group size.
export function parseAutofillCsv(text) {
  const lines = String(text || '').split(/\r?\n/);
  let section = null; // 'profiles' | 'rules' | 'options'
  const profiles = new Map(); // code -> { code, label, name, slots: Map<slot, {registrationId, postCode}> }
  const order = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('### AUTOFILL PROFILES')) { section = 'profiles'; continue; }
    if (line.startsWith('### AUTOFILL RULES')) { section = 'rules'; continue; }
    if (line.startsWith('### AUTOFILL OPTIONS')) { section = 'options'; continue; }

    const f = splitCsvLine(line);
    if (section === 'profiles') {
      if (/^profile id$/i.test(f[0] || '')) continue; // header row
      const code = f[0];
      if (!/^c\d+$/i.test(code)) continue;
      const name = f[1] || code;
      profiles.set(code, { code, name, label: groupLabelFromProfileName(name), slots: new Map() });
      order.push(code);
    } else if (section === 'rules') {
      if (/^rule id$/i.test(f[0] || '')) continue; // header row
      // Rule ID, Type, Name, Value, Site, Mode, Profile
      const fieldName = f[2] || '';
      const value = f[3] || '';
      const code = f[6] || '';
      const m = /registrations[^0-9]*(\d+)[^a-z]*(registrationid|postcode)/i.exec(fieldName);
      if (!m) continue;
      const profile = profiles.get(code);
      if (!profile) continue;
      const slot = Number(m[1]);
      const entry = profile.slots.get(slot) || { registrationId: '', postCode: '' };
      if (m[2].toLowerCase() === 'registrationid') entry.registrationId = value.trim();
      else entry.postCode = value.trim();
      profile.slots.set(slot, entry);
    }
  }

  return order.map((code) => {
    const p = profiles.get(code);
    const members = [...p.slots.entries()]
      .sort((a, b) => a[0] - b[0])
      .map(([, e]) => e)
      .filter((e) => e.registrationId || e.postCode);
    return { code: p.code, name: p.name, label: p.label, members };
  });
}

// ---------------------------------------------------------------------------
// The fill routine (embedded in every bookmarklet)
// ---------------------------------------------------------------------------

// Runs with two variables in scope: M (array of [registrationId, postCode])
// and L (the group label). Deliberately old-school JS (no arrow functions,
// template literals, let/const) so it runs on any browser someone might be
// using on the day. Keep it self-contained - it cannot reference anything
// from this module.
//
// Matching strategy, in order:
//   1. inputs whose id OR name matches registrations…N…RegistrationId /
//      …Postcode (case-insensitive; covers registrations_0__RegistrationId,
//      registrations[0].RegistrationId and reasonable variants);
//   2. failing that, inputs by class (See Tickets uses .numeric / .postcode)
//      or by id containing "egistration" / "ostcode", paired up in order.
// Values are written through the native setter and followed by input/change
// events, so plain, jQuery-validated AND React forms all see a real edit.
export const FILL_SOURCE = `
(function(){
  function nat(el, v) {
    var proto = Object.getPrototypeOf(el);
    var d = Object.getOwnPropertyDescriptor(proto, 'value') || Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value');
    if (d && d.set) { d.set.call(el, v); } else { el.value = v; }
    try { el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); }
    catch (e) { var ev = document.createEvent('HTMLEvents'); ev.initEvent('change', true, false); el.dispatchEvent(ev); }
  }
  function find(i, kind) {
    var re = new RegExp('registrations[^0-9]*' + i + '[^a-z0-9]+' + kind + '$', 'i');
    var ins = document.querySelectorAll('input');
    for (var k = 0; k < ins.length; k++) {
      var e = ins[k];
      if (re.test(e.id || '') || re.test(e.name || '')) return e;
    }
    return null;
  }
  var slots = [];
  for (var i = 0; i < 20; i++) {
    var r = find(i, 'registrationid'), p = find(i, 'postcode');
    if (!r && !p) break;
    slots.push([r, p]);
  }
  if (!slots.length) {
    var regs = document.querySelectorAll('input.numeric, input[id*="egistration"], input[name*="egistration"]');
    var posts = document.querySelectorAll('input.postcode, input[id*="ostcode"], input[name*="ostcode"]');
    for (var j = 0; j < Math.max(regs.length, posts.length); j++) slots.push([regs[j] || null, posts[j] || null]);
  }
  if (!slots.length) {
    alert('Bus Wankers: no registration boxes found on this page. Are you on the Glastonbury registration page?');
    return;
  }
  var filled = 0;
  for (var s = 0; s < slots.length; s++) {
    var m = M[s] || ['', ''];
    if (slots[s][0]) nat(slots[s][0], m[0]);
    if (slots[s][1]) nat(slots[s][1], m[1]);
    if (m[0] && slots[s][0]) filled++;
  }
  var missing = M.length > slots.length ? M.slice(slots.length) : [];
  var msg = 'Bus Wankers - ' + L + ': filled ' + filled + ' of ' + M.length + ' people.';
  if (missing.length) {
    msg += ' This page only has ' + slots.length + ' slots, so NOT entered: ' + missing.map(function (x) { return x[0]; }).join(', ') + '.';
  }
  msg += ' Check the boxes, then click Proceed.';
  try {
    var old = document.getElementById('bw-fill-banner'); if (old) old.parentNode.removeChild(old);
    var b = document.createElement('div');
    b.id = 'bw-fill-banner';
    b.textContent = msg + ' (click to dismiss)';
    b.setAttribute('style', 'position:fixed;top:0;left:0;right:0;z-index:2147483647;background:' + (missing.length ? '#b3261e' : '#1a7f37') + ';color:#fff;font:15px/1.4 Arial,sans-serif;padding:12px 16px;text-align:center;box-shadow:0 2px 6px rgba(0,0,0,.3);cursor:pointer');
    b.onclick = function () { if (b.parentNode) b.parentNode.removeChild(b); };
    document.body.appendChild(b);
    setTimeout(function () { if (b.parentNode) b.parentNode.removeChild(b); }, 15000);
  } catch (e) { alert(msg); }
})();
`;

// Postcodes go in upper case with no spaces - that's how the See Tickets
// form displays them (text-transform: uppercase) and how the roster has
// them; it also avoids a trailing-space mismatch against the registration.
const normalisePostcode = (s) => String(s || '').replace(/\s+/g, '').toUpperCase();

const membersToTuples = (members) =>
  members.map((m) => [String(m.registrationId || '').trim(), normalisePostcode(m.postCode)]);

// The complete bookmarklet source for one group, as plain JavaScript. Wrapped
// in its own function so M and L never leak onto the host page as globals.
export function bookmarkletSource(group) {
  const M = JSON.stringify(membersToTuples(group.members));
  const L = JSON.stringify(`Group ${group.label}`);
  return `(function(){var M=${M},L=${L};${FILL_SOURCE}})();`;
}

// The javascript: URL to put in the bookmark. Percent-encoded so nothing in
// the source (quotes, #, spaces) can break the URL; browsers decode
// javascript: URLs before running them.
export function bookmarkletHref(group) {
  return `javascript:${encodeURIComponent(bookmarkletSource(group))}`;
}

// A sensible bookmark name: "Glasto 2027 - Fill Group A".
export const bookmarkletTitle = (group, year) => `Glasto ${year} - Fill Group ${group.label}`;

// Runs the identical fill routine against THIS page (the Test Form tab), so
// "Try it on the Test Form" exercises exactly what the bookmark will do.
export function runFillOnThisPage(group) {
  const M = membersToTuples(group.members);
  const L = `Group ${group.label}`;
  // eslint-disable-next-line no-new-func
  const fn = new Function('M', 'L', FILL_SOURCE);
  fn(M, L);
}
